### ISSUE TITLE
quality of the inversion

### ISSUE THREAD

**Issue by ariel415el** [zer0int/CLIP-ViT-visualization#1]
Hey, seems like you took inspiration from [this repo](https://github.com/hamidkazemi22/vit-visualization/tree/main)
Any idea why the inversions you show are way less sharp than the ones shown on the repo I mentioned?

**Comment by zer0int** [comment]
Hi there!

Yes, as cited in my readme.md, it is based on the repo you mentioned.

Regarding sharpness of the image, see my code comment:

```
    # coefficient=0.0005 -> sharp and noisy features; coefficient=0.005 -> balanced; coefficient=0.05 -> soft, blurry, muddy
    tv = 1.0
    coefficient=0.005
```

If you prefer very noisy (but sharp, not blurry), try `0.0000005` for the total variation (TV) coefficient, for example.
